// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class ProfileNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 480
    let windowHeight: Int = 360

    // MARK: - Window Title
    let windowTitle: String = "AI4All - Plus Edition (Profile)"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_profile.png"
    let imageWidth: Int = 480
    let imageHeight: Int = 360
}
