name: AI4All

repository: https://github.com/sheldonrobinson/AI4AII.git

sdkPath: auto

packages:
  - apps/*
  - packages/*
  - packages/*/example
  - packages/serious-python/src/*

ignore:
  # e.g. ignore example apps
  # - 'packages/*/src/*'

command:
  bootstrap:
    dependencies:
      # chat ui
      flutter_chat_ui: ^2.9.1
      flutter_chat_types: ^3.6.2
      flutter_chat_core: ^2.8.0
      flyer_chat_text_message: ^2.5.1
      flyer_chat_image_message: ^2.2.2
      flyer_chat_system_message: ^2.1.13
      flyer_chat_file_message: ^2.2.3
      flyer_chat_text_stream_message: ^2.2.6
      # ai
      agenix: ^3.0.0
      dart_mcp: ^0.3.3
      mcp_toolkit: ^0.3.0
      mcp_llm: ^1.0.2
      mcp_server: ^1.0.3
      mcp_client: ^1.0.2
      flutter_mcp: ^1.0.4
      flutter_mcp_ui_core: ^0.2.3
      flutter_mcp_ui_runtime: ^0.2.5
      flutter_mcp_ui_generator: ^0.2.4
      flutter_ai_toolkit: ^0.10.0
      flutter_ai_providers: ^0.3.4+1
      sherpa_onnx: ^1.12.1
      langchain: ^0.8.0+1
      langchain_core: ^0.4.0+1
      # widgets
      flutter_expandable_fab: ^2.5.2
      grouped_list: ^6.0.0
      holdable_button: ^0.0.12
      hold_to_confirm_button: ^0.0.2
      flutter_link_previewer: ^4.1.2
      drop_down_list: ^2.0.0
      sliver_sticky_collapsable_panel: ^3.0.0
      flutter_slidable: ^4.0.0
      expansion_tile_list: ^2.0.0
      accordion: ^2.6.0
      readmore_expandable_text: ^0.0.3
      expansion_tile_group: ^2.3.0
      persistent_bottom_nav_bar_v2: ^6.1.0
      google_nav_bar: ^5.0.7
      easy_settings: ^1.0.2
      ultimate_navigation_bar: ^0.1.9
      icons_plus: ^5.0.0
      adaptive_dialog: ^2.5.0
      adaptive_dialog_manager: ^2.1.2
      flutter_platform_alert: ^0.8.0
      info_popup: ^4.3.2
      alert_info: ^0.0.6
      elegant_notification: ^2.5.1
      flutter_popup_card: ^0.0.6
      on_popup_window_widget: ^0.0.14
      # layout
      flutter_staggered_grid_view: ^0.7.0
      flutter_adaptive_scaffold: ^0.3.3+1
      enough_platform_widgets: ^1.1.1
      adaptive_display: ^0.0.3
      # data
      pro_binary: ^2.0.0
      pro_mpack: ^2.0.2
      json_serializable: ^6.10.0
      json_annotation: ^4.9.0
      freezed: ^3.0.6
      freezed_annotation: ^3.1.0
      yaml: ^3.1.3
      yaml_writer: ^2.1.0
      yaml_edit: ^2.2.2
      xml: ^6.5.0
      # ui
      elementary: ^3.2.0
      fluentui_system_icons: ^1.1.273
      fluent_ui: ^4.13.0
      flutter_spinkit: ^5.2.2
      flutter_inappwebview: ^6.1.5
      motion_toast: ^2.14.0
      whiteboard: ^1.0.0
      signature: ^6.3.0
      disclosure: ^2.2.0
      getwidget: ^5.0.0
      gpt_markdown: ^1.1.4
      about: ^2.2.0
      pref: ^2.8.0
      animations: ^2.1.0
      animated_text_kit: ^4.3.0
      glow_container: ^1.0.1
      ai_glow: ^0.0.2
      uikit_flutter: ^0.0.4
      easy_date_timeline: ^2.0.9
      dynamic_timeline_tile_flutter: ^0.0.4
      timelines_plus: ^1.0.7
      timeline_tile_plus: ^0.0.3
      flutter_dropdown_plus: ^3.0.0
      showcaseview: ^5.0.1
      showcaseview_skipbutton: ^2.2.0
      awesome_flutter_extensions: ^1.3.0
      read_more_text_plus: ^1.0.1
      choice: ^2.3.2
      # settings
      flutter_settings_screens: ^0.3.4
      card_settings_ui: ^2.0.1
      flutter_settings_ui: ^3.0.1
      shared_preferences: ^2.5.3
      encrypt_shared_preferences: ^0.9.9
      # splash/loading screen
      native_splash_screen: ^3.0.0 #destop
      flutter_native_splash: ^2.4.7 #mobile
      loader_overlay: ^5.0.0
      image_circular_progress: ^1.0.1
      quick_actions: ^1.1.0
      intro_slider: ^4.2.5
      desktop_window: ^0.4.2
      window_manager: ^0.5.1
      window_manager_extra: ^0.5.3
      window_manager_plus: ^1.0.5
      window_size:
        git:
          url: https://github.com/google/flutter-desktop-embedding.git
          path: plugins/window_size
      # graphics
      sdl3: ^2.4.1
      visibility_detector: ^0.4.0+2
      opencv_core: ^1.4.3
      opencv_dart: ^1.4.3
      dartcv4: ^1.1.8
      # audio
      record: ^6.0.0
      flutter_recorder: ^1.1.1
      waveform_flutter: ^1.2.0
      siri_wave: ^2.3.0
      audio_service: ^0.18.16
      mp_audio_stream: ^0.2.2
      flutter_soloud: ^3.0.0-pre.0
      pro_miniaudio: ^0.0.11
      coast_audio: ^1.0.0
      fvp: ^0.31.2
      # identity
      flutter_udid: ^4.0.0
      ulid: ^2.0.1
      uuid: ^4.5.1
      cuid2: ^3.1.0
      # events
      async: ^2.13.0
      flutter_streamer: ^2.3.0
      stream_transform: ^2.1.1
      event: ^3.1.0
      once: ^1.7.0
      eventsubscriber: ^3.0.0
      stream_channel: ^2.1.4
      # database
      sembast_sqflite: ^2.2.1
      sembast: ^3.8.5+1
      sqflite: ^2.4.2
      sqflite_common_ffi: ^2.3.6
      objectbox: ^4.3.0
      orange: ^1.2.1
      # business logic
      june: ^1.0.0+1
      rxdart: ^0.28.0
      bloc_ease: ^1.3.0 
      flutter_bloc: ^9.1.1
      get: ^4.7.2
      pro_validator: ^2.0.1
      bit_array: ^2.2.1
      cancellable: ^2.2.4
      sanitize_html: ^2.1.0
      basics: ^0.10.0
      # tuple: ^2.0.2
      basic_utils: ^5.8.2
      # file
      cross_cache: ^1.0.5
      open_file: ^3.5.10
      mime: ^2.0.0
      cross_file: ^0.3.4+2
      file_selector: ^1.0.3
      file_picker: ^10.3.3
      filesystem_picker: ^4.1.0
      image_picker: ^1.1.2
      path_provider: ^2.1.5
      path: ^1.9.1
      glob: ^2.1.3
      dio: ^5.9.0
      # io
      pigeon: ^25.3.2
      w_common: ^3.2.0
      messaging: ^0.3.1
      # url_launcher: ^6.3.1
      permission_handler: ^12.0.1
      background_downloader: ^9.2.2
      flutter_download_manager: ^0.5.5
      # remote
      rfw: ^1.0.31
      # utils
      graphs: ^2.3.2
      string_scanner: ^1.4.1
      markdown: ^7.3.0
      html: ^0.15.6
      bitmask: ^1.0.1
      super_clipboard: ^0.9.1
      super_drag_and_drop: ^0.9.1
      country_code_picker: ^3.3.0
      flutter_typeahead: ^5.2.0
      flutter_memory_info: ^0.0.3
      thumbnailer: ^3.1.0
      asset_cache: ^2.2.0
      mu_state: ^2.0.0+4
      byte_converter: ^2.2.0
      feedback: ^3.2.0
      feedback_gitlab: ^3.0.0
      flet: ^0.28.3
      flutter_local_notifications: ^19.3.0
      interval_tree: ^0.4.1
      package_info_plus: ^9.0.0
      device_info_plus: ^11.5.0
      connectivity_plus: ^7.0.0
      open_share_plus: ^2.0.0
      provider: ^6.1.5
      beautiful_soup_dart: ^0.3.0
      meta: ^1.16.0
      characters: ^1.4.0
      convert: ^3.1.2
      timeago: ^3.7.1
      collection: ^1.19.1
      os_detect: ^2.0.3
      built_value: ^8.10.1
      menubar:
        git:
          url: https://github.com/google/flutter-desktop-embedding.git
          path: plugins/menubar
      built_collection:
        git:
          url: https://github.com/google/built_collection.dart
      hierarchical_state_machine:
        git:
          url: https://github.com/google/hierarchical-state-machine.dart
      quiver: ^3.2.2
      state_machine: ^3.0.1
      async_state_builder: ^0.4.2
      chunked_stream: ^1.4.2
      flutter_secure_storage: ^9.2.4
      state_watcher: ^0.1.0
      share_plus: ^12.0.1
      wakelock_plus: ^1.3.2
      tokenizer: ^1.0.0
      acyclic_steps: ^0.11.2
      log_pro: ^0.0.4
      logging: ^1.3.0
      diffutil_dart: ^4.0.1
      # i18n
      intl: ^0.20.2
      intl_translation: ^0.20.1
      intl4x: ^0.13.0
      easy_localization: ^3.0.7+1
      messages: ^0.2.0
      messages_serializer: ^0.2.1
      messages_shrinker: ^0.2.1
      devicelocale: ^0.8.1
      language_code: ^0.5.5
      # add-ons
      hooks: ^0.20.1
      data_assets: ^0.19.3
      code_assets: ^0.19.6
      mutex: ^3.1.0
      native_synchronization: ^0.3.1
      nativeapi: ^0.1.0-dev.2
      app_runner: ^2.2.2
      dependency_initializer: ^3.0.0
      upgrade: ^0.0.8
      upgrader: ^11.5.0
      app_links: ^6.4.0
      source_helper: ^1.3.5
      code_builder: ^4.10.1
      ffi: ^2.1.4
      plugin_platform_interface: ^2.1.8
      device_preview_plus: ^2.4.2
#      serious_python: ^0.9.3
#        path: packages/serious-python/src/serious_python
      # mobile
      android_package_installer: ^0.0.3
      asset_delivery: ^1.1.0
      online_assets:
        git:
          url: https://github.com/yamashita-room-335/online_assets.git
    dev_dependencies:
      msix: ^3.16.12
      flutter_lints: ^6.0.0
      flutter_launcher_icons: ^0.14.4
      built_value_generator: ^8.10.1
      ffigen: ^19.1.0
      build_runner: ^2.10.1
      hooks_runner: ^0.22.1
      messages_builder: ^0.2.1
      native_splash_screen_cli: ^3.0.0
      very_good_analysis: ^10.0.0
#    hooks:
#      post: melos run launcher_icon   

scripts:
  format:package:
    description: "Run `dart format` in a specific package."
    run: melos exec -- dart format .
    packageFilters:
      flutter: true
  analyze:package:
    description: "Run `dart analyze` in a specific package."
    run: melos exec -- dart analyze .
    packageFilters:
      flutter: true
  launcher_icon:
    description: "Update Flutter app's launcher icon in a specific package."
    exec: dart run flutter_launcher_icons:generate
    packageFilters:
      dependsOn: flutter_launcher_icons
  df_asset:
    description: "Generate asset classes from asset directories."
    run: melos exec -- dart run dart_fusion asset
    packageFilters:
      flutter: true
  df_model:
    description: "Update models by generating toJSON, fromJSON and copyWith based on given annotation."
    run: melos exec -- dart run dart_fusion model
    packageFilters:
      flutter: true
  df_localize:
    description: "Generate localization classes from JSON files."
    run: melos exec -- dart run dart_fusion localize
    packageFilters:
      flutter: true
  
