#ifndef _UNNU_CE_CONSTANT_H
#define _UNNU_CE_CONSTANT_H

const char* id2label[] = {
   "O", "B-ANIMAL", "I-ANIMAL", "B-DISEASE", "I-DISEASE", "B-DISCIPLINE", "I-DISCIPLINE",
   "B-LANGUAGE", "I-LANGUAGE", "B-EVENT", "I-EVENT", "B-FOOD", "I-FOOD", "B-ARTIFACT", "I-ARTIFACT",
   "B-MEDIA", "I-MEDIA", "B-GROUP", "I-GROUP", "B-ORG", "I-ORG", "B-PER", "I-PER", "B-STRUCT", "I-STRUCT",
   "B-LOC", "I-LOC", "B-PLANT", "I-PLANT", "B-MONEY", "I-MONEY", "B-BIOLOGY", "I-BIOLOGY", "B-MEASURE", "I-MEASURE",
   "B-SUPER", "I-SUPER", "B-CELESTIAL", "I-CELESTIAL", "B-LAW", "I-LAW", "B-SUBSTANCE", "I-SUBSTANCE",
   "B-PART", "I-PART", "B-CULTURE", "I-CULTURE", "B-PROPERTY", "I-PROPERTY", "B-FEELING", "I-FEELING",
   "B-PSYCH", "I-PSYCH", "B-RELATION", "I-RELATION", "B-DATETIME", "I-DATETIME", "B-ASSET", "I-ASSET"
}
  

#endif // _UNNU_CE_CONSTANT_H